name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Get NPM cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm

      - name: Install dependencies
        run: npm install --prefix cgt-front-2

      - run: npm run build --prefix cgt-front-2

      - uses: a7ul/tar-action@master
        with:
          command: c
          cwd: "./"
          files: |
            cgt-front-2/dist/
            cgt-front-2/captain-definition
          outPath: deploy.tar

      - name: Deploy Front App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME_FRONT }}'
          token: 'd4fd70f8466974c828e8ec9b48f738bf7431498096da58e96c02b5c2dcd984c9'
